src/objects/AccountableCode__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Member</label>
        <type>Checkbox</type>
    </fields>
    <label>Accountable Code</label>
    <nameField>
        <displayFormat>R{0000000000}</displayFormat>
        <label>Accountable Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accountable Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Entry_Text__c</fullName>
        <label>Entry Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value_Date__c</fullName>
        <label>Value Date</label>
        <type>Date</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <displayFormat>Rel-{000000000}</displayFormat>
        <label>Accounting Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Entry_Details__c.object
<CustomObject>
    <fields>
        <fullName>Accountable_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Accountable Code</label>
        <referenceTo>AccountableCode__c</referenceTo>
        <relationshipLabel>Accounting Entry Details</relationshipLabel>
        <relationshipName>Accounting_Entry_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accounting_Entry_Parent__c</fullName>
        <label>Accounting Entry Parent</label>
        <referenceTo>Accounting_Entry__c</referenceTo>
        <relationshipLabel>Accounting Entry Details</relationshipLabel>
        <relationshipName>Accounting_Entry_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Debt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Debt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Accounting Entry Details</relationshipLabel>
        <relationshipName>Accounting_Entry_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ordinal__c</fullName>
        <label>Ordinal</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Accounting Entry Details</label>
    <nameField>
        <label>Accounting Entry Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entry Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>MemberName__c</fullName>
        <label>Member Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M{000000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T{000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/REntryDetailsController.cls
public class REntryDetailsController {
    private String transactionName;
    private String valueDate;
    private String text;
    private String entryCode;
    private String createdBy;
    public REntryDetailsController(){
        this.entryCode = ApexPages.currentPage().getParameters().get('entryCode');
        Accounting_Entry__c entry = [SELECT Entry_Text__c,Transaction__r.Description__c,Value_Date__c,
                                     CreatedBy.Name FROM Accounting_Entry__c
                                     WHERE Name =:this.entryCode];
        this.transactionName=entry.Transaction__r.Description__c;
        this.valueDate=entry.Value_Date__c.format();
        this.text=entry.Entry_Text__c;
        this.createdBy = entry.CreatedBy.Name;
    }
    public List<Ordinal>getEntryDetails(){
        List<Ordinal>retOrdinals=new List<Ordinal>();        
        List<Accounting_Entry_Details__c> ordinals=[SELECT Accountable_Code__r.Description__c,Amount__c,
                                                    Debt__c,Member__r.MemberName__c,Ordinal__c 
                                                    FROM Accounting_Entry_Details__c WHERE
                                                    Accounting_Entry_Parent__r.Name=:this.entryCode
                                                    ORDER BY Ordinal__c];
        for(Accounting_Entry_Details__c ordinal:ordinals){
            Ordinal aux = new Ordinal();
            aux.ordinal = ordinal.Ordinal__c;
            aux.accName = ordinal.Accountable_Code__r.Description__c;
            if(ordinal.Member__r.MemberName__c!=null){
                aux.member = ordinal.Member__r.MemberName__c;
            }
            else{
                aux.member = '';
            }
            if(ordinal.Debt__c){
                aux.debt = String.valueOf(ordinal.Amount__c);
                aux.credit = '';
            }
            else{
                aux.credit = String.valueOf(ordinal.Amount__c);
                aux.debt = '';
            }
            retOrdinals.add(aux);
        }
        return retOrdinals;
    }
    public class Ordinal{
        public Decimal ordinal {get; set;}
        public String accName {get; set;}
        public String member {get; set;}
        public String debt {get; set;}
        public String credit {get; set;}
    }
    public String getEntryCode(){
        return this.entryCode;
    }
    public String getTransactionName(){
        return this.transactionName;
    }
    public String getValueDate(){
        return this.valueDate;
    }
    public String getText(){
        return this.text;
    }
    public String getCreatedBy(){
        return this.createdBy;
    }
}