src/objects/AccountableCode__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Accountable Code</label>
    <nameField>
        <displayFormat>R{0000000000}</displayFormat>
        <label>Accountable Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accountable Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Balance__c.object
<CustomObject>
    <fields>
        <fullName>Accountable_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Accountable Code</label>
        <referenceTo>AccountableCode__c</referenceTo>
        <relationshipLabel>Balance</relationshipLabel>
        <relationshipName>Balance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Balance</label>
    <nameField>
        <label>Balance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Balance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RBalanceController.cls
public class RBalanceController {
    private Decimal sumBalance=0;
    public Decimal getSumBalance(){
        return this.sumBalance;
    }
    public List<BalanceDetails> getBalanceDetails(){
        List<BalanceDetails> balanceDetailsRet = new List<BalanceDetails>();
        for(AccountableCode__c accCode:[SELECT Name,Description__c,(SELECT ID,Balance__c FROM Balance__r)FROM AccountableCode__c ORDER BY Name]){
            BalanceDetails balance = new BalanceDetails();
            balance.accountableCode = accCode.Name;
            balance.accountableName = accCode.Description__c;
            balance.balance = 0;
            for(Balance__c bal:accCode.Balance__r){
                balance.balance += bal.Balance__c;
                sumBalance+=bal.Balance__c;
            }
            if(balance.balance!=0){
                balanceDetailsRet.add(balance);
            }
        }
        return balanceDetailsRet;
    } 
    public class BalanceDetails{
        public String accountableCode {get; set;}
        public String accountableName {get; set;}
        public Decimal balance {get; set;}
        public String getUrl(){
            if(RRequest.deviceDetection()){
                return URL.getSalesforceBaseUrl().toExternalForm() + '/apex/RBalanceDetailsM?accCode=' + accountableCode;            
            }
            return URL.getSalesforceBaseUrl().toExternalForm() + '/apex/RBalanceDetails?accCode=' + accountableCode;            
        }
    }
}