src/objects/AccountableCode__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Member</label>
        <type>Checkbox</type>
    </fields>
    <label>Accountable Code</label>
    <nameField>
        <displayFormat>R{0000000000}</displayFormat>
        <label>Accountable Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accountable Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Entry__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unposted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value_Date__c</fullName>
        <label>Value Date</label>
        <type>Date</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <displayFormat>Rel-{000000000}</displayFormat>
        <label>Accounting Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Entry_Details__c.object
<CustomObject>
    <fields>
        <fullName>Accountable_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Accountable Code</label>
        <referenceTo>AccountableCode__c</referenceTo>
        <relationshipLabel>Accounting Entry Details</relationshipLabel>
        <relationshipName>Accounting_Entry_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accounting_Entry_Parent__c</fullName>
        <label>Accounting Entry Parent</label>
        <referenceTo>Accounting_Entry__c</referenceTo>
        <relationshipLabel>Accounting Entry Details</relationshipLabel>
        <relationshipName>Accounting_Entry_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Debt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Debt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Accounting Entry Details</relationshipLabel>
        <relationshipName>Accounting_Entry_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accounting Entry Details</label>
    <nameField>
        <label>Accounting Entry Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entry Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Balance__c.object
<CustomObject>
    <fields>
        <fullName>Accountable_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Accountable Code</label>
        <referenceTo>AccountableCode__c</referenceTo>
        <relationshipLabel>Balance</relationshipLabel>
        <relationshipName>Balance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Balance</relationshipLabel>
        <relationshipName>Balance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Balance</label>
    <nameField>
        <label>Balance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Balance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>MemberName__c</fullName>
        <label>Member Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M{000000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T{000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RBalanceDetailsController.cls
public class RBalanceDetailsController {
    private String balanceDescription;
    private String accountableCode;
    private Boolean analyzeByMember;
    private Boolean sentMember;
    private String member =null;
    private String memberName =null;
    private Decimal balanceAmmout;
    public RBalanceDetailsController(){
        String accCode = ApexPages.currentPage().getParameters().get('accCode');
        this.member = ApexPages.currentPage().getParameters().get('member');              
        this.sentMember =(member!=null);
        Member__c currMem=null;
        if(this.sentMember){
            currMem=[SELECT MemberName__c From Member__c WHERE Name =:this.member];
            this.memberName =currMem.MemberName__c;
        }
        this.accountableCode = accCode;
        AccountableCode__c mayor = [SELECT Name,Description__c,Member__c,
                                    (SELECT ID,Balance__c,Member__c FROM Balance__r)
                                    FROM AccountableCode__c WHERE Name =:accCode];
        this.analyzeByMember = mayor.Member__c;
        this.balanceAmmout =0;
        for(Balance__c bal:mayor.Balance__r){
            if(this.analyzeByMember && this.sentMember){
                if(bal.Member__c==currMem.Id){
                    this.balanceAmmout += bal.Balance__c;
                }
            }else{
                this.balanceAmmout += bal.Balance__c;
            }
        }
        this.balanceDescription=mayor.Description__c;        
    }
    public List<MovementDetail> getBalanceDetails(){
        Decimal balance = 0;
        List<MovementDetail> balanceDetailsRet = new List<MovementDetail>();
        List<Accounting_Entry_Details__c> ordinals =null;
        if(this.analyzeByMember && this.sentMember){
            ordinals =[SELECT Accounting_Entry_Parent__r.Value_Date__c,
                       Accounting_Entry_Parent__r.Transaction__r.Description__c,
                       Accounting_Entry_Parent__r.Name,Amount__c,Debt__c
                       FROM Accounting_Entry_Details__c WHERE
                       Accountable_Code__r.Name=:this.accountableCode AND
                       Accounting_Entry_Parent__r.State__c='Posted' AND
                       Member__r.Name=:this.member
                       ORDER BY Accounting_Entry_Parent__r.Name];
        }
        else{
            ordinals =[SELECT Accounting_Entry_Parent__r.Value_Date__c,
                       Accounting_Entry_Parent__r.Transaction__r.Description__c,
                       Accounting_Entry_Parent__r.Name,Amount__c,Debt__c
                       FROM Accounting_Entry_Details__c WHERE
                       Accountable_Code__r.Name=:this.accountableCode AND
                       Accounting_Entry_Parent__r.State__c='Posted'
                       ORDER BY Accounting_Entry_Parent__r.Name];
        }
        for(Accounting_Entry_Details__c ordinal:ordinals){            
            MovementDetail currMove = new MovementDetail();
            currMove.entryCode = ordinal.Accounting_Entry_Parent__r.Name;            
            Date tmp= ordinal.Accounting_Entry_Parent__r.Value_Date__c;
            currMove.valueDate = tmp.format();
            currMove.concept = ordinal.Accounting_Entry_Parent__r.Transaction__r.Description__c;
            if(ordinal.Debt__c){
                currMove.debt = String.valueOf(ordinal.Amount__c);
                currMove.credit = '';
                balance-=ordinal.Amount__c;
            }
            else{
                currMove.credit = String.valueOf(ordinal.Amount__c);
                currMove.debt =  '';
                balance+=ordinal.Amount__c;
            }  
            currMove.balance = balance;
            balanceDetailsRet.add(currMove);
        }
        return balanceDetailsRet;
    } 
    
    public List<MemberDetail> getmemberDetails(){
        List<MemberDetail> memberDetailsRet = new List<MemberDetail>();
        List<Balance__c> balance = [SELECT Balance__c,Member__r.MemberName__c,Member__r.Name FROM Balance__c
         WHERE Member__c!=null and Accountable_Code__r.name=:this.accountableCode];
        for(Balance__c bal:balance){
            MemberDetail actualMember = new MemberDetail();
            actualMember.memberCode = bal.Member__r.Name;
            actualMember.name =bal.Member__r.MemberName__c;
            actualMember.balance =bal.Balance__c;
            actualMember.accountableCode =this.accountableCode;
            memberDetailsRet.add(actualMember);
        }
        return memberDetailsRet;
    } 
    
    public class MemberDetail{
        public String accountableCode{get; set;}
        public String memberCode {get; set;}
        public String name {get; set;}
        public Decimal balance {get; set;}
        public String getUrl(){
            return URL.getSalesforceBaseUrl().toExternalForm() + '/apex/RBalanceDetails?accCode=' + 
                accountableCode+'&member='+memberCode;
        }
    }
    public class MovementDetail{
        public String entryCode {get; set;}
        public String valueDate {get; set;}
        public String concept {get; set;}
        public String debt {get; set;}
        public String credit {get; set;}
        public Decimal balance {get; set;}
        public String getUrl(){
            return URL.getSalesforceBaseUrl().toExternalForm() + '/apex/REntryDetails?entryCode=' + 
                entryCode;
        }
    }
    public Boolean getAnalyzeByMember(){
        return this.analyzeByMember;
    }      
    public String getBalanceDescription(){
        return this.balanceDescription;
    }
    public String getAccountableCode(){
        return this.accountableCode;
    }
    public Decimal getBalanceAmmout(){
        return this.balanceAmmout;
    }
    public Boolean getSentMember(){
        return this.sentMember;
    }
    public String getMemberName(){
        return this.memberName;
    }
}