src/objects/AccountableCode__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Member</label>
        <type>Checkbox</type>
    </fields>
    <label>Accountable Code</label>
    <nameField>
        <displayFormat>R{0000000000}</displayFormat>
        <label>Accountable Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accountable Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Entry_Text__c</fullName>
        <label>Entry Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unposted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value_Date__c</fullName>
        <label>Value Date</label>
        <type>Date</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <displayFormat>Rel-{000000000}</displayFormat>
        <label>Accounting Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Accounting_Entry_Details__c.object
<CustomObject>
    <fields>
        <fullName>Accountable_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Accountable Code</label>
        <referenceTo>AccountableCode__c</referenceTo>
        <relationshipLabel>Accounting Entry Details</relationshipLabel>
        <relationshipName>Accounting_Entry_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accounting_Entry_Parent__c</fullName>
        <label>Accounting Entry Parent</label>
        <referenceTo>Accounting_Entry__c</referenceTo>
        <relationshipLabel>Accounting Entry Details</relationshipLabel>
        <relationshipName>Accounting_Entry_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Coin__c</fullName>
        <label>Coin</label>
        <picklist>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dollar</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Debt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Debt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Accounting Entry Details</relationshipLabel>
        <relationshipName>Accounting_Entry_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ordinal_Text__c</fullName>
        <label>Ordinal Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Ordinal__c</fullName>
        <label>Ordinal</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Accounting Entry Details</label>
    <nameField>
        <label>Accounting Entry Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Entry Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Balance__c.object
<CustomObject>
    <fields>
        <fullName>Accountable_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Accountable Code</label>
        <referenceTo>AccountableCode__c</referenceTo>
        <relationshipLabel>Balance</relationshipLabel>
        <relationshipName>Balance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Coin__c</fullName>
        <label>Coin</label>
        <picklist>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dollar</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Balance</relationshipLabel>
        <relationshipName>Balance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Balance</label>
    <nameField>
        <label>Balance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Balance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>MemberName__c</fullName>
        <label>Member Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M{000000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T{000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RAccountingEntryController.cls
global class RAccountingEntryController {
    public RAccountingEntryController(){
        
    }
    @RemoteAction
    global static Map<String,Object> start() {
        Map<String,Object> resultMap = new Map<String,Object>();
        List<Transaction__c> lstTransaction = [SELECT Id,Description__c FROM Transaction__c];
        List<Member__c> lstMembers = [SELECT Id,MemberName__c FROM Member__c];
        List<AccountableCode__c> lstAccountableCodes = [SELECT Id,Description__c,Member__c FROM AccountableCode__c];
        resultMap.put('lstTransaction',lstTransaction);
        resultMap.put('lstAccountableCodes',lstAccountableCodes);
        resultMap.put('lstMembers',lstMembers);
        resultMap.put('valueDate',Date.today().format());        
        return resultMap;
    }
    @RemoteAction
    global static void save(String userSelectedEntryJSON){
        System.debug('Received Entry: '+userSelectedEntryJSON);
        Map<String,Object> userSelectedEntry =(Map<String,Object>)JSON.deserializeUntyped(userSelectedEntryJSON);
        Accounting_Entry__c entry = saveEntry(userSelectedEntry);
        countEntry(entry);
        
        List<Contact> contacts = [SELECT Email FROM Contact WHERE Notify_Transaction__c=true];
        if(contacts.size()!=0){
            String[]toAddresses= new String[contacts.size()];
            Integer i = 0;
            for(Contact contact:contacts){
                toAddresses[i]=contact.Email;
                i++;
            }
            Accounting_Entry__c entryAux =[SELECT Name FROM Accounting_Entry__c WHERE Id =:entry.Id];
            
            REntryDetailsController redc = new REntryDetailsController(true);
            redc.fillHeader(entryAux.Name);
            String subject = 'New entry posted! '+ redc.getTransactionName();
            List<REntryDetailsController.Ordinal> ordinals=redc.externalDetails(entryAux.Name);
            String body='';
            
            body+=entryAux.Name+' '+redc.getTransactionName()+'\n\n';
            body+='Value Date: ' +redc.getValueDate() +'\t';
            body+='Created By: ' +redc.getCreatedBy() +'\n';
            body+='Text: ' +(redc.getText()==null?'':redc.getText())+'\n\n';
            
            body+='\tConcept\t\t\tMember\t\t\tDebt\t\tCredit\n';
            for(REntryDetailsController.Ordinal ord:ordinals){
                body+=ord.ordinal+'\t'+ord.accName+'\t\t\t'+ord.member+'\t\t\t'+
                    ord.debt+'\t\t'+ord.credit+'\n';
            }
            
            try{
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();        
                mail.setToAddresses(toAddresses);        
                mail.setSubject(subject);
                mail.setPlainTextBody(body);
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            }catch(Exception e){
                System.debug('Error during sending mail, limit exceeded: '+e.getMessage());
            }
        }
        return;
    }
    public static void countEntry(Accounting_Entry__c entry){
        Id entryId = entry.Id;
        for(Accounting_Entry_Details__c ordinal:[SELECT Id,Accountable_Code__c,Amount__c,Coin__c,Debt__c,Member__c FROM Accounting_Entry_Details__c WHERE Accounting_Entry_Parent__c =: entryId]){
            Id accCod = ordinal.Accountable_Code__c;
            String coinM = ordinal.Coin__c;
            Id memberID = ordinal.Member__c;
            List<Balance__c> lstBalance =[SELECT Balance__c,Id FROM Balance__c WHERE
                                          Accountable_Code__c =:accCod  AND
                                          Coin__c =: coinM AND
                                          Member__c =: memberID LIMIT 1];
            if(lstBalance.size()==0){
                Balance__c newBalance = new Balance__c();
                newBalance.Accountable_Code__c=ordinal.Accountable_Code__c;
                newBalance.Coin__c=ordinal.Coin__c;
                newBalance.Member__c=ordinal.Member__c;
                newBalance.Balance__c=ordinal.Debt__c?ordinal.Amount__c*(-1):ordinal.Amount__c;
                insert newBalance;
            }
            else{
                Balance__c existingBalance = lstBalance.get(0);
                existingBalance.Balance__c=ordinal.Debt__c?(existingBalance.Balance__c-ordinal.Amount__c):(existingBalance.Balance__c+ordinal.Amount__c);
                    update existingBalance;
            }
        }
        entry.State__c = 'Posted';
        update entry;
    }
    public static Accounting_Entry__c saveEntry(Map<String,Object>userSelectedEntry){
        Accounting_Entry__c entry = new Accounting_Entry__c(); 
        entry.State__c = 'Unposted';
        entry.Transaction__c = Id.valueOf((String)userSelectedEntry.get('transaction'));
        entry.Value_Date__c = Date.parse((String)userSelectedEntry.get('valueDate'));
        entry.Entry_Text__c = (String)userSelectedEntry.get('entryText');
        insert entry;
        
        List<Object>jsonOrdinals = (List<Object>)userSelectedEntry.get('ordinals');
        List<Accounting_Entry_Details__c>ordinals = new List<Accounting_Entry_Details__c>();
        for(Object jsonOrdinal:jsonOrdinals){
            Map<String,Object>mapJsonOrdinal = (Map<String,Object>)jsonOrdinal;
            Accounting_Entry_Details__c ordinal = new Accounting_Entry_Details__c();
            ordinal.Accounting_Entry_Parent__c = entry.Id;
            ordinal.Accountable_Code__c = Id.valueOf((String)mapJsonOrdinal.get('accCode'));
            ordinal.Amount__c = (Decimal)mapJsonOrdinal.get('ammount');
            ordinal.Coin__c = (String)mapJsonOrdinal.get('coin');
            ordinal.Debt__c = (Boolean)mapJsonOrdinal.get('debt');
            
            String strIdMember = (String)mapJsonOrdinal.get('member');
            if(strIdMember.compareTo('')!=0){
                ordinal.Member__c = Id.valueOf(strIdMember);
            }
            ordinal.Ordinal__c = (Decimal)mapJsonOrdinal.get('ordinal');
            ordinal.Ordinal_Text__c = (String)mapJsonOrdinal.get('text');
            ordinals.add(ordinal);
        }
        insert ordinals;
        return entry; 
    }
}