src/objects/Accounting_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Entry_Text__c</fullName>
        <label>Entry Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unposted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Accounting Entries</relationshipLabel>
        <relationshipName>Accounting_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value_Date__c</fullName>
        <label>Value Date</label>
        <type>Date</type>
    </fields>
    <label>Accounting Entry</label>
    <nameField>
        <displayFormat>Rel-{000000000}</displayFormat>
        <label>Accounting Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T{000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/REntriesController.cls
public class REntriesController {
    public List<EntryHeader> getEntries(){
        List<EntryHeader> entriesRet= new List<EntryHeader>();        
        List<Accounting_Entry__c> entries = [SELECT Name,Entry_Text__c,Transaction__r.Description__c,
                                             Value_Date__c,CreatedBy.Name FROM Accounting_Entry__c
                                             WHERE State__c='Posted' ORDER by Name DESC];
        for(Accounting_Entry__c entry:entries){
            EntryHeader eh= new EntryHeader();
            eh.transactionName=entry.Transaction__r.Description__c;
            eh.valueDate=entry.Value_Date__c.format();
            eh.entryCode=entry.Name;
            eh.createdBy=entry.CreatedBy.Name;
            entriesRet.add(eh);
        }        
        return entriesRet;
    }
    public class EntryHeader{
        public String transactionName{get; set;}
        public String valueDate{get; set;}
        public String entryCode{get; set;}
        public String createdBy{get; set;}
        public String getUrl(){
            return URL.getSalesforceBaseUrl().toExternalForm() + '/apex/REntryDetails?entryCode=' + 
                entryCode;
        }
    }    
}